### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by rlacjfjin** [ed-lam/bcp-mapf#3]
1. Cplex  must be needed?
2. Whether scip-7.0.2 version is work done?

Actually, I met cmake error in building using CLION.

**Comment by ed-lam** [comment]
Cplex is needed for now. Gurobi and SCIP 7 will be supported in a new version in the coming weeks.

What problem are you having in CLion? I also use it and have no problems.

**Comment by shaoxiang-zheng** [comment]
Can I ask that how to configure CMakefile.txt if I want to use Gurobi in Clion?

**Comment by ed-lam** [comment]
Gurobi has been supported for some time but it is now the preferred LP solver over CPLEX.
